=== beldenge/CFGReader/src/data/xml/CFG.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:simpleType name="SymbolType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="Terminal"/>
		<xs:enumeration value="NonTerminal"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="ProductionType">
	<xs:attribute name="symbol" type="xs:string" use="required"/>
	<xs:attribute name="type" type="SymbolType" use="required"/>
</xs:complexType>

<xs:complexType name="ExpansionType">
	<xs:sequence>
		<xs:element name="Production" type="ProductionType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="RuleType">
	<xs:sequence>
		<xs:element name="Expansion" type="ExpansionType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="non-terminal" type="xs:string" use="required"/>
</xs:complexType>

<xs:element name="ContextFreeGrammar">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Rule" type="RuleType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="first-rule" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>

</xs:schema>

=== beldenge/CFGReader/src/data/xml/EnglishSentenceCFG.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
Copyright 2015 George Belden

This file is part of CFGReader.

CFGReader is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

CFGReader is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with CFGReader.  If not, see <http://www.gnu.org/licenses/>.
 -->
<ContextFreeGrammar first-rule="Sentence"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="CFG.xsd">
	<Rule non-terminal="Sentence">
		<Expansion>
			<Production symbol="NounPhrase" type="NonTerminal" />
			<Production symbol="VerbPhrase" type="NonTerminal" />
		</Expansion>
	</Rule>
	<Rule non-terminal="NounPhrase">
		<Expansion>
			<Production symbol="Article" type="Terminal" />
			<Production symbol="Noun" type="Terminal" />
		</Expansion>
		<Expansion>
			<Production symbol="Noun" type="Terminal" />
		</Expansion>
	</Rule>
	<Rule non-terminal="VerbPhrase">
		<Expansion>
			<Production symbol="Verb" type="Terminal" />
		</Expansion>
		<Expansion>
			<Production symbol="Verb" type="Terminal" />
			<Production symbol="NounPhrase" type="NonTerminal" />
		</Expansion>
	</Rule>
</ContextFreeGrammar>
